---
title: "git_01"
author: "Adam Ayala"
date: "Fall 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
“Just the place for a Snark!” the Bellman cried,  
As he landed his crew with care;  
Supporting each man on the top of the tide  
By a finger entwined in his hair.  

“Just the place for a Snark! I have said it twice:    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
The house had gone to bring again  
To the midnight sky a sunset glow.  
Now the chimney was all of the house that stood,  
Like a pistil after the petals go.  

The barn opposed across the way,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
“The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
There are two kinds of people on earth to-day;  
Just two kinds of people, no more, I say.  

Not the sinner and saint, for it’s well understood,  
The good are half bad and the bad are half good.  

Not the rich and the poor, for to rate a man’s wealth,  
You must first know the state of his conscience and health.  

Not the humble and proud, for in life’s little span,  
Who puts on vain airs is not counted a man.  

Not the happy and sad, for the swift flying years  
Bring each man his laughter and each man his tears.  

No; the two kinds of people on earth I mean,  
Are the people who lift and the people who lean.  

Wherever you go, you will find the earth’s masses  
Are always divided in just these two classes.  

And, oddly enough, you will find, too, I ween,  
There’s only one lifter to twenty who lean.  
 
In which class are you? Are you easing the load  
Of overtaxed lifters, who toil down the road?  

Or are you a leaner, who lets others share  
Your portion of labor, and worry and care?  